
### model
model_name_or_path: E:/code/qwen2-vl-2b-instruct

### method
stage: rm
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: train
dataset_dir: E:/code/DataSets/PPDDataTest
template: qwen2_vl
cutoff_len: 1024
max_samples: 3000
overwrite_cache: true
preprocessing_num_workers: 1

### output
output_dir: E:/code/qwen2-vl-2b-instruct_rm
logging_steps: 10
save_steps: 100
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 2
learning_rate: 1.0e-5